config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
	devise_for :users, controllers: {
			omniauth_callbacks: "users/omniauth_callbacks"
	}

	root 'pages#index'

	get 'search' => 'pages#main'
	get 'about' => 'pages#about'
	get 'admin' => 'pages#admin'
	get 'settings' => 'pages#settings'
	get 'compare' => 'compare#compare'

	get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
    	get :get_new_messages
    end
  end

	resources :settings, only: [:create, :update]

	resources :level1s do
		resources :comments, only: [:index, :new]
		resources :descriptions, only: :index
		resources :resources, only: [:index, :new]
  		resources :level2s do
			patch :remove, on: :member 
  			resources :level3s
  		end
    collection do
      get :filter_records
    end
    get :get_details, on: :member
	end

	resources :level2s, except: [:new, :create] do
		resources :comments, only: [:index, :new]
		resources :descriptions, only: :index
		resources :resources, only: [:index, :new]
		patch :add_level1, on: :member
  	resources :level3s
    get :get_details, on: :member
  end

	resources :level3s, except: [:new, :create] do
		resources :comments, only: [:index, :new]
		resources :resources, only: [:index, :new]
		resources :descriptions, only: :index
    get :get_details, on: :member
	end
	
	resources :comments

  resources :descriptions
  
  resources :resources do
    get :show_resource, on: :member
  	resources :comments, only: [:index, :new] 
  	resources :descriptions, only: :index
  end

	resources :users do
		resources :favourites
	end

	resources :clicks
	resources :favourites

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	# Comment(id: integer, content: string, user_id: integer, commentable_id: integer, commentable_type: string, created_at: datetime, updated_at: datetime)

	belongs_to :commentable, polymorphic: true
	belongs_to :user

	# <return> [Level1, Level2, Level3]
	def object
		commentable_type.constantize.find(commentable_id)
	end

	self.per_page = 30
	attr_accessor :distance_in_time
	validates_presence_of :user, :content, :commentable_type, :commentable_id

	# <overview>  Add :distance_in_time to objects from collection
	# <return> ActiveRecord Collection
	scope :calculate_distance_in_time, lambda{|granularity=nil| 
		time = nil
		all.each do |object|

			this_time = object.created_at
			object.distance_in_time = time ? time_distance(time, this_time, granularity) : 0.01
 
			time = this_time
		end
	}

	# <overview> Distance between two dates
	# <param> [Datetime] First date
	# <param> [Datetime] Second date
	# <param> [String] Granularity
	# <return>	[Integer]
	def self.time_distance(a, b, granularity)
		return 0 unless granularity

		case granularity
		when "minute"
			distance = (a.day - b.day) * 60 * 24 + (a.hour - b.hour) * 60 * (a.minute - b.minute)
		when "day"
			distance = (a.year - b.year) * 365 + (a.month - b.month) * 30 + (a.day - b.day)
		when "month"
			distance = (a.year - b.year) * 12 + (a.month - b.month)
		when "year"
			distance = a.year - b.year
		when "decade"
			distance = (a.year - b.year) / 10
		end
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :authenticate_user!
	before_filter :fetch_comment, except: [:index, :create, :new]
	before_filter :authenticate_owner, only: [:update, :destroy]
	before_filter :fetch_object, only: [:index, :new]



	def new
		@comment = Comment.new

		respond_to do |format|
        	format.html
        	format.js
    	end
	end

	def index

		if @object
			# Retrieve all comments belonging to @object ordered by params[:order] or created_at
			@comments = @object.comments.order(params[:order] || "created_at desc")
		else
			# Retrieve all comments ordered by params[:order] or created_at
			@comments = Comment.all.order(params[:order] || "created_at desc")
		end

		# Pagination
		if params[:page]
			@comments = @comments.paginate(:page => params[:page])
		end

		# Add :distance_in_time field to all elements of @comments collection
		if params[:granularity]
			@comments = @comments.calculate_distance_in_time(params[:granularity])
		end
		
		respond_to do |format|
        	format.html
        	format.js
        	format.json { render json: @comments, status: 200 }
    	end
	end


	def create
		@comment = current_user.comments.new(comment_params)

		if @comment.save
			respond_to do |format|
	        	format.html { redirect_to @comment.object, notice: 'Comment was successfully created.'}
	        	format.json { render json: @comment, status: 200}
	        	format.js
	    	end
		else
			respond_to do |format|
				format.json { render status: 422}
	        	format.html { render :new}
	        	format.js
	    	end	
		end
	end

	def update	
		if @comment.update(comment_params)
			respond_to do |format|
	        	format.html { redirect_to :back, notice: 'Comment was successfully updated.'}
	        	format.json { render json: @comment, status: 200}
	    	end
		else
			respond_to do |format|
	        	format.html { render :back}
	        	format.json { render json: @comment.errors, status: 422 }
	    	end			
		end
	end

	def destroy
	    if @comment.destroy      
	    	respond_to do |format|
	        	format.html {redirect_to :back, notice: 'Comment was successfully destroyed.'}
	        	format.json { head 204}
	    	end
	    else
	    	respond_to do |format|
	    		format.html { redirect_to :back, notice: "Comment wasn't destroyed"}
	    		format.json { render json: @comment.errors, status: :unprocessable_entity }
	    	end
	    end
	end

	private



	def authenticate_owner
		block_access unless (@comment.user == current_user) || current_user.admin? || current_user.super_user?
	end

	def comment_params
    	params.require(:comment).permit(:commentable_id, :commentable_type, :content)
  	end 

  	def fetch_comment
  		@comment = Comment.find(params[:id])
  	end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
.description
	.col-md-12
		%strong= comment.created_at.strftime("%B %d, %Y")
		%em 
			by
			= link_to comment.user.name, comment.user
			about
			= link_to comment.object.name, comment.object
		%p= comment.content

app/views/comments/_comment_view.html.haml
.timeline-block{"data-item-type" => "comment", "data-item-id" => comment.id}
  %ul.comment.pd-left10.pd-right10.pd-top10
    %li
      .person-img.fl-left
        .person-img-inner
          = image_tag(comment.user.avatar.present? ? comment.user.avatar.url : "silhouette96.png")
      .person-name
        %p.text-right.time-st=comment.created_at.strftime("%B %d, %Y")
        %p.text-left.color-blue.ellipsis=comment.user.name
    %li.clearfix
    %li.ft-size12.font-weight-300=truncate comment.content, length: 140
    %li.text-right.bottom-border

app/views/comments/_comments.html.haml
%table.table.table-bordered
	%thead
		%tr
			%th ID
			%th User
			%th Target
			%th Message
			%th Created
			%th Delete
	%tbody
		- comments.each do |comment|
			%tr
				%td= comment.id
				%td= link_to comment.user.name, comment.user
				%td= link_to comment.object.name, comment.object
				%td= comment.content
				%td= comment.created_at.strftime("%B %d, %Y")
				%td= link_to "Delete", comment, method: :delete

app/views/comments/_form.html.haml
= simple_form_for :comment, :html => {class: 'new-comment-form', novalidate: false}, url: comments_path, remote: local_assign[:remote_true] ? true : false do |f|
  = f.input :commentable_id, :as => :hidden, :input_html => { :value => @object.id }
  = f.input :commentable_type, :as => :hidden, :input_html => { :value => @object.class.to_s }
  %span.map-close-button.icon
  %span.text-camera-icon.icon
  = f.input :content, as: :text, placeholder: "your comment...", required: true, label: false
  .form-group
    = f.button :submit, "Add", class: "btn btn-default"

app/views/comments/_form_modal.html.haml
#myModal.modal.fade.form{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
	.modal-dialog.small-modal
		.modal-content
        
			.modal-body
				%button.close{"data-dismiss" => "modal", "aria-hidden" => "true" } ×
				.row
					#resource-item
						.row
							.col-md-10.col-md-offset-1
								= simple_form_for :comment, :html => {class: 'form-horizontal', novalidate: false}, url: comments_path, remote: true do |f|
									= f.input :commentable_id, :as => :hidden, :input_html => { :value => @object.id }
									= f.input :commentable_type, :as => :hidden, :input_html => { :value => @object.class.to_s }
									= f.input :content, as: :text, placeholder: "Description", required: false, label: false
									.form-group
										= f.button :submit, "Save", class: "btn btn-default"

app/views/comments/_timeline.html.haml
.timeline{"data-type"=>"comment"}
	%header 
		%h5 Comments

		- if controller_name != "favourites"
			%select
				%option{value: "off"} Off
				%option{value: "day"}	Day
				%option{value: "month"} Month
				%option{value: "year"} Year
				%option{value: "decade"} Decade
	%section
		.timeline-body
			.timeline-wrapper
				.timeline-line
				.timeline-collection
					- if collection.present?
						= render partial: "comments/timeline_item" , collection: collection, as: :comment

app/views/comments/_timeline_item.html.haml
- if params[:granularity] && comment.distance_in_time && comment.distance_in_time != 0
  .distance-in-time{style: "margin-top: #{15 * comment.distance_in_time}px"}
    %date= display_date(comment.created_at, params[:granularity])


.timeline-block{"data-item-type" => "comment", "data-item-id" => comment.id}
  .timeline-point
    = link_to  edit_comment_path(comment) do
      .roundblock
  .timeline-content.comment
    %header
      %figure
        = image_tag(comment.user.avatar.present? ? comment.user.avatar.url : "silhouette96.png", width: "40px", height: "40px")
        %figcaption
          = comment.user.name
          %date
            = comment.created_at.strftime("%B %d, %Y")
    %article
      .comment-content
        = truncate comment.content, length: 140 

        - if comment.user == current_user
          %i.fa.fa-cog

    - if comment.user == current_user 
      %footer
        .comment-input{"data-url" => comment_path(comment)}
          %input{value: comment.content}
          %button{"data-action" => "save"} Save
          %button{"data-action" => "cancel"} Cancel

      

app/views/comments/create.js.haml
- if params[:comming_from] == "expansive"
  TimeLine.reloadComments();
- else 
  $('#myModal').modal('hide');
  $('textarea[name="comment[content]"]').val('');
  if (window.timelines.currentTimeline){window.timelines.config["comment"].timeline.reloadTimeline();} else {$.ajax({ dataType: "script", url: "#{polymorphic_path([@comment.object, Comment])}"});}

app/views/comments/index.html.haml
.container
	.row
		.col-md-12.text-center
			%h1.page-head Comments
		.col-md-12
			- if @comments.any?
				= render partial: "comments", locals: {comments: @comments}
			- else
				%p
					There is no comments
					- if @object
						for 
						= link_to @object.name, @object

app/views/comments/index.js.haml
- if params[:new_view]
  TimeLine.commentMessageContainer.html('#{escape_javascript(render partial: "pages/expansive_right")}');
- else
  - if params[:page] && params[:page].to_i > 1
    - @comments.each do |comment|
      var newElement = '#{escape_javascript(render partial: "timeline_item" ,  locals: {comment: comment})}';
      window.timelines.addElement("comment",newElement);
  - else
    var collection = '#{escape_javascript(render partial: "timeline_item" , collection: @object ? @comments : nil, as: :comment)}';
    window.timelines.render("comment", collection);

app/views/comments/new.html.haml
.container
	.row
		.col-md-12.text-center
			%h1.page-head Add comment
		.col-md-4.col-md-offset-4
			= simple_form_for :comment, :html => {class: 'form-horizontal', novalidate: false}, url: comments_path do |f|
				= f.input :commentable_id, :as => :hidden, :input_html => { :value => @object.id }
				= f.input :commentable_type, :as => :hidden, :input_html => { :value => @object.class.to_s }
				= f.input :content, as: :text, placeholder: "Description", required: false, label: false
				.form-group
					= f.button :submit, "Save", class: "btn btn-default"

app/views/comments/new.js.haml
$('body').append('#{escape_javascript(render partial: 'form_modal')}');
$('#myModal').modal('show');

$('#myModal').on('hidden.bs.modal', function () {$("#myModal").remove();});