config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
	devise_for :users, controllers: {
			omniauth_callbacks: "users/omniauth_callbacks"
	}

	root 'pages#index'

	get 'search' => 'pages#main'
	get 'about' => 'pages#about'
	get 'admin' => 'pages#admin'
	get 'settings' => 'pages#settings'
	get 'compare' => 'compare#compare'

	get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
    	get :get_new_messages
    end
  end

	resources :settings, only: [:create, :update]

	resources :level1s do
		resources :comments, only: [:index, :new]
		resources :descriptions, only: :index
		resources :resources, only: [:index, :new]
  		resources :level2s do
			patch :remove, on: :member 
  			resources :level3s
  		end
    collection do
      get :filter_records
    end
    get :get_details, on: :member
	end

	resources :level2s, except: [:new, :create] do
		resources :comments, only: [:index, :new]
		resources :descriptions, only: :index
		resources :resources, only: [:index, :new]
		patch :add_level1, on: :member
  	resources :level3s
    get :get_details, on: :member
  end

	resources :level3s, except: [:new, :create] do
		resources :comments, only: [:index, :new]
		resources :resources, only: [:index, :new]
		resources :descriptions, only: :index
    get :get_details, on: :member
	end
	
	resources :comments

  resources :descriptions
  
  resources :resources do
    get :show_resource, on: :member
  	resources :comments, only: [:index, :new] 
  	resources :descriptions, only: :index
  end

	resources :users do
		resources :favourites
	end

	resources :clicks
	resources :favourites

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def create
    recipients = User.where(id: conversation_params[:recipients])
    @conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
    if request.xhr?
      get_conversations
      render :show
    else
      flash[:success] = "Your message was successfully sent!"
      redirect_to conversation_path(@conversation)
    end

  end

  def update_session
   session[:message_time] =  session[:message_time] = DateTime.now.strftime('%a, %d %b %Y %H:%M:%S')
  end

  def show
    get_conversations
    update_session 
  end

  def get_conversations
    @receipts = conversation.receipts_for(current_user)
    # mark conversation as read
    conversation.mark_as_read(current_user)
  end

  def get_new_messages
    @new_messages = conversation.messages.where("sender_id <> ? AND created_at > ? ", current_user.id, session[:message_time].to_datetime)
    update_session 
  end

  def reply
    current_user.reply_to_conversation(conversation, message_params[:body])
    update_session 
    if request.xhr? 
      get_conversations
      render :show
    else
      flash[:notice] = "Your reply message was successfully sent!"
      redirect_to conversation_path(conversation)
    end
  end

  def destroy
    conversation.move_to_trash(current_user)
    if request.xhr? 
      get_conversations
      render :show
    else
      flash[:success] = 'The conversation was moved to trash.'
      redirect_to conversation_path(conversation)
    end
  end

  def untrash
    conversation.untrash(current_user)
    if request.xhr? 
      get_conversations
      render :show
    else
      flash[:success] = 'The conversation was restored.'
      redirect_to conversation_path(conversation)
    end
  end

  private

  def conversation_params
    params.require(:conversation).permit(:subject, :body,recipients:[])
  end

  def message_params
    params.require(:message).permit(:body, :subject)
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.haml
.media
  .media-left
    = link_to user_path(conversation.originator) do
      = image_tag(conversation.originator.avatar.url, class: "media-object")
  .media-body
    %h4.media-heading
      = conversation.originator.mailboxer_name
      %br
        %small
          %b Subject:
          = conversation.subject
        %br
          %small
            %b Date:
            = conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p")
    = truncate conversation.messages.last.body, length: 145
    = link_to "View", conversation_path(conversation), remote: true

app/views/conversations/_form.html.haml
= form_for :conversation, url: :conversations, remote: true, html: { class: "" } do |f|
  
  .form-group
    = f.label :recipients
    = f.select(:recipients, User.where("id <> ?", current_user.id).collect {|p| [ p.mailboxer_name, p.id ] }, {}, { multiple: true , class: "form-control chosen-select" })
  .form-group
    = f.label :subject
    = f.text_field :subject, placeholder: "Subject", class: "form-control"
  .form-group
    = f.label :message
    = f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 4

  = f.submit "Send Message", class: "btn btn-success"

:javascript
  $(function(){
    $('.chosen-select').chosen({
      allow_single_deselect: true,
      no_results_text: 'No results matched',
    });
  });

app/views/conversations/_message.html.haml
.media
  .media-left
    / user avators can go here
    %a{:href => "#"}
  .media-body
    %h4.media-heading
      = message.sender.mailboxer_name
      %br
        %small
          %b Subject:
          = message.subject
        %br
          %small
            %b Date:
            = message.created_at.strftime("%A, %b %d, %Y at %I:%M%p")
    = message.body

app/views/conversations/_messages.html.haml
- @receipts.each do |receipt|
  - message = receipt.message
  = render partial: "conversations/message", locals: {message: message}

app/views/conversations/_show.html.haml
.row
  .spacer
  .col-md-12
    = link_to "Compose", new_conversation_path, remote: true, class: "btn btn-success"
    .spacer
  .col-md-4
    .panel.panel-default
      .panel-body
        = render 'mailbox/folders'
  .col-md-8
    .pull-right{style: "width:200px;"}
      = link_to "load messages", get_new_messages_conversations_path(id: @conversation.id), remote: true, class: "load_new_messages", style: "display:none;"
      = link_to "Resfresh", conversation_path(@conversation), remote: true, class: "btn btn-success btn-success pull-right"

      - if @conversation.is_trashed?(current_user)
        = button_to 'Restore', untrash_conversation_path(@conversation), remote: true, class: 'btn btn-xs btn-info pull-right ', method: :post
      - else
        = button_to 'Move to trash', conversation_path(@conversation), remote: true, class: 'btn btn-xs btn-danger pull-right', method: :delete, data: {confirm: 'Are you sure?'} 
    .panel.panel-default
      #conversation_messages.panel-body
        = render partial: 'conversations/messages'
      .panel-footer
        / Reply Form
        = form_for :message, url: reply_conversation_path(@conversation), remote: true do |f|
          .form-group
            = f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control"
          = f.submit "Reply", class: 'btn btn-danger pull-right'
        .clearfix


  

app/views/conversations/get_new_messages.js.haml
-if not @new_messages.blank?
  var htmlData = '#{escape_javascript(render partial: "conversations/message" , collection:  @new_messages)}';
  $('#conversation_messages').append(htmlData);

app/views/conversations/new.html.haml
= render partial: 'mailbox/folder_view', locals: { is_conversation: true }

app/views/conversations/new.js.haml
var htmlData = '#{escape_javascript(render partial: "mailbox/folder_view", locals: { is_conversation: true })}';
MailBox.renderContent(htmlData);

app/views/conversations/show.html.haml
= render partial: 'conversations/show'

app/views/conversations/show.js.haml
var htmlData = '#{escape_javascript(render partial: 'conversations/show')}';
MailBox.renderContent(htmlData);

if (typeof loadMessages != undefined){
clearInterval(loadMessages);
}

var loadMessages = setInterval(function(){$('a.load_new_messages').trigger('click')}, 15000);