config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
	devise_for :users, controllers: {
			omniauth_callbacks: "users/omniauth_callbacks"
	}

	root 'pages#index'

	get 'search' => 'pages#main'
	get 'about' => 'pages#about'
	get 'admin' => 'pages#admin'
	get 'settings' => 'pages#settings'
	get 'compare' => 'compare#compare'

	get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
    	get :get_new_messages
    end
  end

	resources :settings, only: [:create, :update]

	resources :level1s do
		resources :comments, only: [:index, :new]
		resources :descriptions, only: :index
		resources :resources, only: [:index, :new]
  		resources :level2s do
			patch :remove, on: :member 
  			resources :level3s
  		end
    collection do
      get :filter_records
    end
    get :get_details, on: :member
	end

	resources :level2s, except: [:new, :create] do
		resources :comments, only: [:index, :new]
		resources :descriptions, only: :index
		resources :resources, only: [:index, :new]
		patch :add_level1, on: :member
  	resources :level3s
    get :get_details, on: :member
  end

	resources :level3s, except: [:new, :create] do
		resources :comments, only: [:index, :new]
		resources :resources, only: [:index, :new]
		resources :descriptions, only: :index
    get :get_details, on: :member
	end
	
	resources :comments

  resources :descriptions
  
  resources :resources do
    get :show_resource, on: :member
  	resources :comments, only: [:index, :new] 
  	resources :descriptions, only: :index
  end

	resources :users do
		resources :favourites
	end

	resources :clicks
	resources :favourites

end

app/models/description.rb
class Description < ActiveRecord::Base
	# Description(id: integer, content: text, descriptable_id: integer, descriptable_type: string, created_at: datetime, updated_at: datetime)

	belongs_to :descriptable, polymorphic: true
	validates_presence_of :content

	# <return> [Level1, Level2, Level3]
	def object
		descriptable_type.constantize.find(descriptable_id)
	end

	
end

app/controllers/descriptions_controller.rb
class DescriptionsController < ApplicationController
	before_filter :authenticate_user!
	before_filter :fetch_description, except: [:index, :create]

	before_filter :authenticate_owner, only: [:update, :destroy]
	before_filter :fetch_object, only: :index


	def index
		@descriptions = @object ? @object.descriptions : Description.all
		respond_to do |format|
			format.js
        	format.json { render json: @descriptions, status: 200 }
    	end
	end



	def create
		@description = Description.new(description_params)

		if @description.save
			respond_to do |format|
	        	format.html { redirect_to :back, notice: 'Description was successfully created.'}
	        	format.json { render json: @description, status: 200}
	    	end
		else
			respond_to do |format|
				format.json { render status: 422}
	        	format.html { redirect_to :back, notice: 'Description was not created.'}
	    	end	
		end
	end


	def update	
		if @description.update(description_params)
			respond_to do |format|
	        	format.html { redirect_to :back, notice: 'Description was successfully updated.'}
	        	format.json { render json: @description, status: 200}
	    	end
		else
			respond_to do |format|
	        	format.html { redirect_to :back, notice: 'Description was not updated.'}
	        	format.json { render json: @description.errors, status: 422 }
	    	end			
		end
	end

	def destroy
	    if @description.destroy      
	    	respond_to do |format|
	        	format.html {redirect_to :back, notice: 'Description was successfully destroyed.'}
	        	format.json { head 204}
	    	end
	    else
	    	respond_to do |format|
	    		format.html { redirect_to :back, notice: "Description wasn't destroyed"}
	    		format.json { render json: @description.errors, status: :unprocessable_entity }
	    	end
	    end
	end

	private

	def authenticate_owner
		block_access unless (@description.object.user == current_user) || current_user.admin? || current_user.super_user?
	end

	def description_params
    	params.require(:description).permit(:descriptable_id, :descriptable_type, :content)
  	end 

  	def fetch_description
  		@description = Description.find(params[:id])
  	end

end

app/helpers/descriptions_helper.rb
module DescriptionsHelper
end

app/views/descriptions/_description.html.haml
.description
	.col-md-12
		%strong= description.created_at.strftime("%B %d, %Y")
		%p= description.content

app/views/descriptions/_form.html.haml
.container
	= simple_form_for :description, :html => {class: 'form-horizontal', novalidate: false}, url: descriptions_path do |f|
		= f.input :descriptable_id, :as => :hidden, :input_html => { :value => object.id }
		= f.input :descriptable_type, :as => :hidden, :input_html => { :value => object.class.to_s }
		= f.input :content, as: :text, placeholder: "Description", required: false, label: false
		.form-group
			= f.button :submit, "Save", class: "btn btn-default"

app/views/descriptions/_viewer.html.haml
%header

  - if object

    - unless current_user.follow? object
      = link_to "New favourite", favourites_path(favourite: {favouritable_type: object.class.to_s, favouritable_id: object.id}), class: "btn btn-primary new-resource btn-xs btn-branded", method: "post", remote: true
    - else
      = link_to "Unfollow", object.favourites.where(user: current_user).last, class: "btn btn-primary new-resource btn-xs btn-branded", method: "delete", remote: true


    = link_to "Comment", polymorphic_path(object) + "/comments/new", class: "btn btn-primary new-resource btn-xs btn-branded", remote: true

%section
  - if !object.present?
    %p No item selected
  - else
    - if (object.user == current_user) || current_user.admin? || current_user.super_user?
      %a{href: "/#{object.class.name.pluralize.downcase + '/' + object.id.to_s + '/edit'}", "data-remote" => "true"}
        %p= object.description.present? ? (raw object.description) : "Add Content"
    - else
      %a{href: "/#{object.class.name.pluralize.downcase + '/' + object.id.to_s}"}
        %p= object.description.present? ? (raw object.description) : "No description"

app/views/descriptions/index.js.haml
var description = '#{escape_javascript(render partial: "descriptions/viewer", locals: {object: @object})}';
window.timelines.addDescriptionToViewer(description)