config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
	devise_for :users, controllers: {
			omniauth_callbacks: "users/omniauth_callbacks"
	}

	root 'pages#index'

	get 'search' => 'pages#main'
	get 'about' => 'pages#about'
	get 'admin' => 'pages#admin'
	get 'settings' => 'pages#settings'
	get 'compare' => 'compare#compare'

	get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
    	get :get_new_messages
    end
  end

	resources :settings, only: [:create, :update]

	resources :level1s do
		resources :comments, only: [:index, :new]
		resources :descriptions, only: :index
		resources :resources, only: [:index, :new]
  		resources :level2s do
			patch :remove, on: :member 
  			resources :level3s
  		end
    collection do
      get :filter_records
    end
    get :get_details, on: :member
	end

	resources :level2s, except: [:new, :create] do
		resources :comments, only: [:index, :new]
		resources :descriptions, only: :index
		resources :resources, only: [:index, :new]
		patch :add_level1, on: :member
  	resources :level3s
    get :get_details, on: :member
  end

	resources :level3s, except: [:new, :create] do
		resources :comments, only: [:index, :new]
		resources :resources, only: [:index, :new]
		resources :descriptions, only: :index
    get :get_details, on: :member
	end
	
	resources :comments

  resources :descriptions
  
  resources :resources do
    get :show_resource, on: :member
  	resources :comments, only: [:index, :new] 
  	resources :descriptions, only: :index
  end

	resources :users do
		resources :favourites
	end

	resources :clicks
	resources :favourites

end

app/models/user.rb
class User < ActiveRecord::Base
  # Fields: ["id", "email", "encrypted_password", "reset_password_token", "reset_password_sent_at", "remember_created_at", "sign_in_count", "first_name", "last_name", "authenticated", "role", "enabled", "avatar_file_name", "avatar_content_type", "avatar_file_size", "avatar_updated_at", "created_at", "updated_at"]
	OAUTH_PROVIDERS = [:google_oauth2, :facebook, :twitter]

	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable,
				 :omniauthable, :omniauth_providers => OAUTH_PROVIDERS

	has_attached_file :avatar, :default_url => ActionController::Base.helpers.asset_path('missing_user.png')
	validates_attachment_content_type :avatar, :content_type => [/\Aimage\/.*\Z/]

	has_many :clicks
	has_many :comments
	has_many :level1s
	has_many :level2s
	has_many :level3s
	has_many :favourites

	validates :email, :presence => true
	validates :role, :presence => true
	
	after_create :check_authentication_mode
  acts_as_messageable

  # <overview> Does this user follow an object
  # <param> object [Level1 || Level2 || Level3]
  # <return> [Boolean] 
	def follow? object
		favourites.where(favouritable_type: object.class.to_s, favouritable_id: object.id).exists?
	end

  # <overview> Full name of the user
  # <return> [String]
  def name
    return "no name" unless first_name || last_name
    (first_name || "") + " " + (last_name || "")
  end

  def mailboxer_name
    return email unless first_name || last_name
    (first_name || "") + " " + (last_name || "")
  end

  def mailboxer_email(object)
    self.email
  end

  # <overview> Does user belong to super users level1
  # <return> [Boolean]
	def super_user?
		role == "super"
	end

  # <overview> Does user belong to admins level1
  # <return> [Boolean]
	def admin?
		(role == "admin") || (email == "admin@admin.com")
	end

	def active_for_authentication?
   	super and self.enabled and (self.authenticated != false)
  end


  # <overview> Message shown to user after authentication if user's account has been disabled or user hasn't been authenticated
	def inactive_message
		if enabled 
			if authenticated
				super
			else
				"Admin has to manually authenticate your account"
			end
		else
			"Your account has been disabled by admin"
		end
	end

	# Create new user from OAUTH provider
	def self.from_omniauth(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
			user.email = auth.info.email
			user.password = Devise.friendly_token[0,20]
			user.first_name = auth.info.name.split(' ',2)[0] || ''   # assuming the user model has a first name
			user.last_name = auth.info.name.split(' ',2)[1] || ''  # assuming the user model has a last name
			user.image = auth.info.image # assuming the user model has an image
		end
	end

  private

  # Modify default value of :authenticated field depending on global settings
	def check_authentication_mode
		if Setting.mode == "open"
			update(authenticated: true)
		else
			update(authenticated: false)
		end
	end


end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  User::OAUTH_PROVIDERS.each do |provider|
    eval "def #{provider.to_s}
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
        set_flash_message(:notice, :success, :kind => '#{provider.to_s.capitalize}') if is_navigational_format?
      else
        session['devise.facebook_data'] = request.env['omniauth.auth']
        flash.notice = 'Please, log in to your account'
        redirect_to new_user_registration_url
      end
    end"
  end

  def failure
    redirect_to root_path
  end

  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!
	before_filter :fetch_user, only: [:show, :edit, :update, :destroy]
	before_filter :authenticate_owner, except: :index


	def index
		@users = User.all
		respond_to do |format|
        	format.html
        	format.json { render json: @users, status: 200 }
    	end
	end

	def show
		respond_to do |format|
        	format.html
        	format.json { render json: @user, status: 200, location: @user}
    	end
	end


	def edit
	end

	def update	

		if @user.update_attributes(user_params)
			respond_to do |format|
	        	format.html { redirect_to @user, notice: 'User was successfully updated.'}
	        	format.js {render json: @user, status: 200}
	        	format.json { render json: @user, status: 200}
	    	end
		else
			respond_to do |format|
	        	format.html { render :edit}
	        	format.js {render nothing: true, status: 500}
	        	format.json { render json: @user.errors, status: 422 }
	    	end			
		end
	end

	def destroy
	    if @user.destroy      
	    	respond_to do |format|
	        	format.html {redirect_to @user, notice: 'User was successfully destroyed.'}
	        	format.json { head 204}
	    	end
	    else
	    	respond_to do |format|
	    		format.html { redirect_to :back, notice: "User wasn't destroyed"}
	    		format.json { render json: @user.errors, status: :unprocessable_entity }
	    	end
	    end
	end

	private

	def authenticate_owner
		block_access unless (@user == current_user) || current_user.admin? || current_user.super_user?
	end

	def user_params
    	params.require(:user).permit(:id, :first_name, :last_name, :email, :enabled, :role, :avatar, :authenticated)
  	end 

  	def fetch_user
  		@user = User.find(params[:id])
  	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= simple_form_for(:user, as: :user, url: session_path(:user), html: {class: "navbar-form navbar-right"}) do |f| 
	.form-group
		= f.input :email, required: true, label: false, placeholder: "Email", :input_html => {class: "form-control", required: true, autocomplete: "off"} 
	.form-group
		= f.input :password, required: true, label: false, placeholder: "Password", :input_html => {class: "form-control", required: true, autocomplete: "off"}      
	.form-group
		= f.button :submit, "Log in", class: "btn"

app/views/users/_user.html.haml
- if current_user.admin? || current_user.super_user?
	%tr
		= simple_form_for user, :html => {novalidate: false} do |f|
			%td= user.id
			%td	
				= f.input :first_name, placeholder: "First name", required: false, label: false, input_html: {required: true, "data-id" => user.id, "data-name" => "first_name"}
			%td= f.input :last_name, placeholder: "Last name", required: false, label: false, input_html: {required: true, "data-id" => user.id, "data-name" => "last_name"}
			%td= f.input :email, as: :email, placegolder: "Email", required: false, label: false, input_html: {required: true, "data-id" => user.id, "data-name" => "email"}
			%td= user.created_at.strftime("%B %d, %Y")
			%td
				= f.input :role, collection: ["user", "admin", "super"], required: false, label: false, input_html: { required: true, "data-id" => user.id, "data-name" => "role"}

			%td= f.input :enabled, as: :boolean, required: false, label: false, input_html: {"data-id" => user.id, "data-name" => "enabled"}
			%td= f.input :authenticated, as: :boolean, required: false, label: false, input_html: {"data-id" => user.id, "data-name" => "authenticated"}
			%td
				.btn-group
					= link_to "Show", user, class: "btn btn-default btn-branded btn-xs"
					= link_to "Delete", user, method: :delete, class: "btn btn-default btn-branded btn-xs"



- else
	%tr
		%td= user.id
		%td= user.first_name
		%td= user.last_name
		%td= user.email
		%td= user.created_at.strftime("%B %d, %Y")
		%td= user.role

		%td= user.enabled ? "Enabled" : "Disabled"
		%td= user.authenticated ? "Authenticated" : "Not authenticated"
		%td
			.btn-group
				= link_to "Show", user, class: "btn btn-default btn-branded btn-xs"
				= link_to "Edit", edit_user_path(user), class: "btn btn-default btn-branded btn-xs"
				= link_to "Delete", user, method: :delete, class: "btn btn-default btn-branded btn-xs"

app/views/users/_users.html.haml
%table.table.table-bordered
	%thead
		%tr
			%th ID
			%th First name
			%th Last name
			%th Email
			%th Created
			%th Role
			%th Enabled
			%th Authenticated
			%th 
	%tbody
		= render users


:javascript
	$("input, select").change(function(e){
		data = {"user": {}};

		if ($(this).hasClass("boolean")){
			data["user"][$(this).data("name")] = $(this).is(':checked') ? 1 : 0; 
		} else {
			data["user"][$(this).data("name")] = $(this).val();
		}

		$.ajax({
			method: "put",
			url: "/users/" + $(this).data("id"),
			data: data,
			dataType: "script"
		})
	});

app/views/users/edit.html.haml
.container
	.row
		.col-md-12.text-center
			%h1.page-head New user
		.col-md-4.col-md-offset-4
			= simple_form_for @user, :html => {class: 'form-horizontal', novalidate: false} do |f|

				= f.input :first_name, placeholder: "First name", required: false, label: "First name"
				= f.input :last_name, placeholder: "Last name", required: false, label: "Last name"

				- if current_user.admin?
					= f.input :role, collection: ["user", "admin", "super"], required: false, label: "Role", input_html: { required: true }
					= f.input :enabled, as: :boolean, required: false, label: "Enabled"
					= f.input :authenticated, as: :boolean, required: false, label: "Authenticated"

				= f.input :email, as: :email, placegolder: "Email", required: false, label: "Email", input_html: {required: true }

				= f.input :avatar, as: :file



				.form-group
					= f.button :submit, "Save", class: "btn btn-default"

			.row
				= link_to "Back", level1s_path

app/views/users/index.html.haml
.container
	.row
		.col-md-12.text-center
			%h1.page-head Users
		.col-md-12
			= render partial: "users", locals: {users: @users}
			

app/views/users/show.html.haml
.container.user-profile
	.row#profile-block
		.col-md-12.text-center
			%h1.page-head= @user.name

	.row
		.col-md-12
			%h4.section-head Basic info
	
	#profile-block
		.row
			.col-md-8
				%dl.dl-horizontal
					.menu-item
						%dt ID:
						%dd= @user.id
					.menu-item
						%dt Name:
						%dd= @user.name
					.menu-item
						%dt Role:
						%dd= @user.role.capitalize
					.menu-item
						%dt Status:
						%dd= @user.enabled ? "Enabled" : "Disabled"

					.menu-item
						%dt Email:
						%dd= @user.email
					.menu-item
						%dt Created:
						%dd= @user.created_at.strftime("%B %d, %Y")

					.menu-item
						%dt Number of comments:
						%dd= @user.comments.count
					.menu-item
						%dt Added to favourite:
						%dd= link_to @user.favourites.count, user_favourites_path(@user)

				.btn-group

					- if current_user.admin? || current_user.super_user?
						= link_to "All", users_path, class: "btn btn-default btn-branded"

					= link_to "Edit", edit_user_path(@user), class: "btn btn-default btn-branded"
					= link_to "Delete", @user, class: "btn btn-default btn-branded", method: "delete"
					= link_to "Back", :back, class: "btn btn-default btn-branded"
			.col-md-4
				%figure
					= image_tag(@user.avatar.url, width: "100%")

	.row#profile-block
		.col-md-12
			%h4.section-head Level1s
		.col-md-12
			- if @user.level1s.any?
				= render partial: "level1s/level1s", locals: {level1s: @user.level1s}
			- else
				%p 
					There is no level1s yet.
					= link_to "Create first", new_level1_path

	.row#profile-block
		.col-md-12
			%h4.section-head Level2s
		.col-md-12
			- if @user.level2s.any?
				= render partial: "level2s/level2s", locals: {level2s: @user.level2s}
			- else
				%p 
					There is no level2s yet.


	.row#profile-block
		.col-md-12
			%h4.section-head Level3s
		.col-md-12
			- if @user.level3s.any?
				=# render partial: "level3s/level3s", locals: {level3s: @user.level3s}
			- else
				%p There is no level3s yet.

	.row#profile-block
		.col-md-12
			%h4.section-head Comments
		- if @user.comments.any?
			= render @user.comments.order("created_at desc")
		- else
			.col-md-12
				%p There is no comments yet